Собрал webpack
f1tZy/mesto pull request #1
Opened 2020-03-22 14:18 UTC by f1tZy

Создали в Git ветку master и develop, в которой разрабатывали функционал.
Fix мелких ошибок в проекте.
Собрал webpack для оптимизации картинок и шрифтов.
CSS-код минимизирован.
JS разбит на модули и переведён бабелем из ES6 в ES5.
Сайт открывается в интернете по адресу: https://f1tzy.github.io/mesto/

2020-03-23 11:08 UTC, aarefiev requested changes
Хорошая работа. Есть все необходимые ветки (master, develop, gh-pages), проект выложен на Github Pages, открывается, функционал частично работает на сайте :cry:. Сайт общается с API по `HTTPS`. Хорошее ридми, но не хватает инструкции о том как развернуть проект. Игнорируются временные файлы. В самой работе используется `webpack`, есть файл `.nojekyll`, настроено хэширование CSS и JS файлов, JS код транспилится в ES5, CSS минифицируется и проставляются префиксы, изображения и шрифты не оптимизируются. При запуске сайта локально ошибок в консоли нет. Локально подключение к API происходит по протоколу `HTTPS` вместо `HTTP`.

Ниже я указал краткий список ошибок и улучшений, которые могут улучшить работу. Развернутые комментарии будут непосредственно в коде.

**Нужно исправить:**
1. Не хватает инструкции как развернуть проект в README.md.
2. В режиме разработки происходит подключение к API по протоколу `HTTPS`.
3. ~Функционал снятия/установки лайка работает не полностью~ (не ошибка, тк является дополнительным заданием).
4. Функционал создания/удаления карточки работает не полностью.

**Можно лучше:**
1. Вынести `targets` в отдельный файл.
2. Указать описание проекта.
3. Внедрить оптимизацию изображений.
4. Внедрить оптимизацию шрифтов.

2020-03-23 11:08 UTC, aarefiev commented on readme.md
> +Версия проекта: v0.0.1
Нужно исправить: не хватает инструкции о том как развернуть проект локально в README.md.
Нужно указать в описании:
- инструкцию о том как развернуть проект локально

Версия указана в `package.json`. По идее при внесении изменений нужно обновлять версию в `package.json`, в `README.md` и пушить тэг в репозиторий. Как об этом пишут в практике. Главное обратить внимание, что `git tag` по-умолчанию не пушится, нужно либо настраивать конфиг, либо писать `git push --tags`.

Дополнительно скину ресурсы, которые помогут его улучшить:
- статья "[Как написать хороший README?](https://medium.com/astrolabe/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%B9-readme-159f88076b26)".
- примеры шаблонов для README:
  - https://gist.github.com/PurpleBooth/109311bb0361f32d87a2,
  - https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

2020-03-23 11:08 UTC, aarefiev commented on babel.config.js
> +        },
Можно лучше: вынести `targets` в отдельный файл.
Благодаря использованию https://github.com/browserslist/browserslist можно задать единые параметры поддержки для многих инструментов, таких как: `babel`, `autoprefixer` и другие.

2020-03-23 11:08 UTC, aarefiev commented on package.json
> +  "description": "",
Можно лучше: указать описание проекта.
Достаточно написать пару слов о проекте в свободной форме, о чем он.

2020-03-23 11:08 UTC, aarefiev commented on webpack.config.js
> +        test: /\.(eot|ttf|woff|woff2)$/,
Можно лучше: внедрить оптимизацию шрифтов: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=ru .

2020-03-23 11:08 UTC, aarefiev commented on webpack.config.js
> +        test: /\.(png|jpg|gif|ico|svg)$/,
Можно лучше: внедрить оптимизацию изображений:
https://www.npmjs.com/package/image-webpack-loader .

2020-03-23 11:08 UTC, aarefiev commented on js/script.js
> +import { Api } from "../js/Api.js";
Нужно исправить: в режиме разработки происходит подключение к API по протоколу `HTTPS`.
В режиме разработки должно быть по протоколу `HTTP`. Потому что режим разработки сам запускается на этом протоколе.

2020-03-23 11:08 UTC, aarefiev commented on js/script.js
> +import { Card } from "../js/Card.js";
Нужно исправить:
- функционал снятия/установки лайка работает не полностью,
- функционал создания/удаления карточки работает не полностью

Реализован только JS, изменения не отравляются на API. В связи с чем, после перезагрузки страницы изменения пропадают. По заданию, если функционал реализован, то он должен работать полностью.

2020-03-24 17:10 UTC, f1tZy commented on js/script.js
> +import { Card } from "../js/Card.js";
функционал создания/удаления карточки по API. Тоже доп задание прошлого курса, не делал из-за жесткого дедлайна. Постараюсь реализовать потом.

2020-03-24 17:10 UTC, f1tZy commented on js/script.js
> +import { Api } from "../js/Api.js";
Исправил

2020-03-24 17:11 UTC, f1tZy commented on package.json
> +  "description": "",
Реализовал

2020-03-24 17:11 UTC, f1tZy commented on babel.config.js
> +        },
Реализовал

2020-03-24 17:11 UTC, f1tZy commented on readme.md
> +Версия проекта: v0.0.1
Реализовал

2020-03-24 17:45 UTC, f1tZy commented on webpack.config.js
> +        test: /\.(png|jpg|gif|ico|svg)$/,
Не исправлял

2020-03-24 17:45 UTC, f1tZy commented on webpack.config.js
> +        test: /\.(eot|ttf|woff|woff2)$/,
Не исправлял

2020-03-25 10:24 UTC, aarefiev approved these changes
Очень хорошо. Критические ошибки исправлены. Новых не обнаружено.
Работа принимается :tada: .

2020-03-31 14:21 UTC, merged